In [24]:
import numpy as np

In [25]:
import matplotlib.pyplot as plt
%matplotlib inline

In [26]:
lista = np.array([1,2,3,4,5,6])
lista

array([1, 2, 3, 4, 5, 6])

In [27]:
lista_1 = np.array([[1,2],[3,4],[5,6]])
lista_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
lista.shape, lista.size

((6,), 6)

In [29]:
lista_1.shape, lista_1.size

((3, 2), 6)

In [30]:
type(lista), type(lista_1)

(numpy.ndarray, numpy.ndarray)

In [36]:
lista_2 = np.arange(0,11,3) #range(od,do,diferencija niza(svaki drugi, treći ...))
lista_2

array([0, 3, 6, 9])

In [42]:
lista_3 = np.linspace(0,11,10)
lista_3

array([  0.        ,   1.22222222,   2.44444444,   3.66666667,
         4.88888889,   6.11111111,   7.33333333,   8.55555556,
         9.77777778,  11.        ])

In [55]:
lista_2 = np.logspace(0,11,3) #range(od,do,diferencija niza(svaki drugi, treći ...))
lista_2

array([  1.00000000e+00,   3.16227766e+05,   1.00000000e+11])

In [83]:
matrica = np.matrix('1,2; 3,4')
matrica_1 = np.matrix('1,1; 2,4')
rez = matrica * matrica_1
rez

matrix([[ 5,  9],
        [11, 19]])