In [35]:
import numpy as np

In [36]:
import scipy as sc

In [37]:
import sympy as sy

In [38]:
import matplotlib.pyplot as plt

In [23]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [25]:
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [26]:
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [27]:
v.shape, M.shape

((4,), (2, 2))

In [28]:
v.size, M.size

(4, 4)

In [30]:
x=np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.linspace(0,10,25)

array([  0.        ,   0.41666667,   0.83333333,   1.25      ,
         1.66666667,   2.08333333,   2.5       ,   2.91666667,
         3.33333333,   3.75      ,   4.16666667,   4.58333333,
         5.        ,   5.41666667,   5.83333333,   6.25      ,
         6.66666667,   7.08333333,   7.5       ,   7.91666667,
         8.33333333,   8.75      ,   9.16666667,   9.58333333,  10.        ])

In [44]:
data = np.genfromtxt('a.csv', skiprows=1, skip_footer=True, delimiter=',', filling_values=0)